from .interfaces import interfacesComponent
from .interface import interfaceComponent
from .subinterfaces import subinterfacesComponent
from .subinterface import subinterfaceComponent
from .oc_ip import oc_ipComponent
from .oc_ipAddresses import oc_ipAddressesComponent
from .oc_ipAddress import oc_ipAddressComponent
from .ethernet import ethernetComponent
from .switchedVlan import switchedVlanComponent
